schema.js
test/compile.js

add openaddresses type to schema

add openaddresses type

---

mappings/partial/multiplier.json
mappings/poi.js
test/poi.js

for storing population information when available (better scoring function)

Adding multiplier type to POIs

---

mappings/poi.js
test/poi.js

Popularity score can be computed based on number of photos taken, number of visitors to a region/point etc
This will be useful with respect to https://github.com/pelias/admin-lookup/issues/5
Fixes pelias/pelias#51

add popularity field

---

README.md

closes https://github.com/pelias/schema/issues/71

remove info in readme about installing the now deprecated elasticsearch plugin

---

integration/bounding_box.js
integration/run.js
mappings/document.js
mappings/partial/boundingbox.json
test/document.js
test/fixtures/expected.json

added `bounding_box` field support

---

.travis.yml
integration/admin_matching.js
integration/bounding_box.js
mappings/document.js
package.json
test/document.js
test/fixtures/expected.json
test/fixtures/new_schema.json

Connected to pelias/api#424
Connects pelias/pelias#258

Rename _abbr properties to _a

---

integration/address_matching.js
mappings/document.js
package.json
test/document.js
test/fixtures/expected.json
test/fixtures/new_schema.json

connected to pelias/pelias#278

Rename address prop to address_parts

---

schema.js
test/fixtures/expected.json

added `borough` support for recent WOF changes

---

integration/analyzer_peliasPhrase.js

add slop tests for https://github.com/pelias/api/pull/489

add slop tests for https://github.com/pelias/api/pull/489

---

package.json
scripts/drop_index.js

Warn when dropping the schema and not connected to localhost

---

mappings/document.js
schema.js
test/document.js
test/fixtures/expected.json

`dependency` was missing from the various analysis and search pieces.

added `dependency` in the various places

---

settings.js

These now live in pelias/config as of https://github.com/pelias/config/pull/36.o
Connects https://github.com/pelias/schema/issues/178

Remove basic Elasticsearch settings

---

configValidation.js
package.json
settings.js
test/configValidation.js
test/run.js
test/settings.js

requires object esclient and string schema.indexName

added validation for configuration

---

mappings/document.js
mappings/partial/postalcode.json
test/document.js
test/fixtures/expected.json

Add postalcode to schema and set analyzer to peliasZip
Connected to pelias/api#350

Add postalcode to parent hierarchy

---

README.md
integration/analyzer_peliasIndexOneEdgeGram.js
integration/analyzer_peliasIndexTwoEdgeGram.js
settings.js
test/fixtures/expected.json
test/settings.js

increase max ngram size from 18->24
resolves https://github.com/pelias/pelias/issues/580
see issue notes for more detail

max ngram size

---

README.md

All that is required for setting up the schema is downloading the node modules and creating the index

Rename "Scripts" section to "Usage"

---

package.json

fix(package): update elasticsearch to version 13.3.1

---

package.json

chore(package): update semantic-release to version 15.0.0

---

.travis.yml
README.md

Connects https://github.com/pelias/pelias/issues/612
Connects https://github.com/pelias/pelias/issues/693

Drop Node.js 4, add Node.js 8

---

scripts/drop_index.js

Just trying to make sure @holman has fewer chances to tweet about us
screwing something up.

Show host when dropping schema that isn't localhost

---

package.json
settings.js

fix(package): update pelias-config to version 3.0.1

---

.travis.yml
integration/address_matching.js
integration/analyzer_peliasPhrase.js
integration/autocomplete_abbreviated_street_names.js
integration/run.js

I have a post-it note on my desk with some small things I wanted to change after merging https://github.com/pelias/schema/pull/328.
See the individual commit messages for more info.

miscellaneous test cleanup

---

integration/analyzer_peliasAdmin.js
integration/analyzer_peliasHousenumber.js
integration/analyzer_peliasIndexOneEdgeGram.js
integration/analyzer_peliasPhrase.js
integration/analyzer_peliasQueryFullToken.js
integration/analyzer_peliasQueryPartialToken.js
integration/analyzer_peliasStreet.js
integration/analyzer_peliasZip.js
integration/run.js

This refactoring was extracted from the bugfix in https://github.com/pelias/schema/pull/367

chore(test): Use more common tools in tests

---

settings.js
test/fixtures/expected.json

remove disused peliasTwoEdgeGramFilter

remove disused peliasTwoEdgeGramFilter

---

configValidation.js
mappings/document.js
package.json
schema.js
test/configValidation.js

pairs with https://github.com/pelias/config/pull/118 & https://github.com/pelias/model/pull/123
more information available on the other PRs

support for dynamically specifying the elasticsearch _type from config

---

scripts/create_index.js
scripts/drop_index.js

this commit was backported from the es7 branch

modernize scripts js

---

scripts/list_analyzers.js

cherry-picked from https://github.com/pelias/schema/pull/412, this PR introduces a new script which can be used to list which fields are present, along with the analyzers and normalizers associated with the field.
example usage:
```bash
node scripts/list_analyzers.js
----------------
list analyzers
----------------
field                            type                             analyzer                  search_analyzer           normalizer
source                           keyword                          n/a                       n/a                       {none}
layer                            keyword                          n/a                       n/a                       {none}
name.*                           text                             peliasIndexOneEdgeGram …
```

add list_analyzers.js script

---

.travis.yml

elasticsearch 7.6.1 has been released, this PR updates Travis

fix(travis): elasticsearch 7.6.1 has been released

---

mappings/document.js
test/fixtures/expected.json

This PR adds new `{placetype}_source` properties and should be merged before pelias/model#128 and pelias/api#1481.
related: pelias/model#128 pelias/api#1481

Add support for custom sources in hierarchy

---

.github/workflows/_integration_tests.yml
.github/workflows/_unit_tests.yml

Connects https://github.com/pelias/pelias/issues/985

CI: Add Node.js 24 to CI
