pelias/schema

schema.js, test/compile.js
add `osmaddress` type to schema.
the idea here is that we start partitioning the address records from OSM in to their own elasticsearch `"type"`
related: https://github.com/pelias/openstreetmap/issues/29
cc/ @hkrishna @sevko @heffergm
=> add osm address type

mappings/partial/admin.json, test/partial-admin.js
```keyword``` analyzer is useful for pin codes but for admin0 and admin1, we'd like to search for ```new york``` or  ```New York``` and always be able to match to ```New York``` using ```match``` query/filter. 
[this is a work in progress] - Problem with this PR is that ```'Great Britain'``` might get broken into ```['great', 'britain']``` 
Maybe all we need is a lowercase filter?? [Lets Discuss]
As per https://github.com/pelias/api/pull/68
Fixes pelias/pelias#43
=> change the way we analyze admin fields so we can search on them

mappings/boundary.js, mappings/partial/category.json, mappings/poi.js, test/boundary.js, test/partial-category.js, test/poi.js, test/run.js
Relates pelias/openstreetmap#33
add a new `'category'` field to mapping to `poi` and `boundary` layer schemas.
this PR will facilitate adopting a taxonomy as outlined in https://github.com/pelias/pelias/wiki/Taxonomy-v1 and allow queries such as https://gist.github.com/missinglink/dd1dcdb377a0ff271890
=> add categories to schema

.travis.yml, integration/analyzer_peliasOneEdgeGram.js, integration/analyzer_peliasPhrase.js, integration/analyzer_peliasShingles.js, integration/analyzer_peliasTwoEdgeGram.js, integration/dynamic_templates.js, integration/run.js, integration/validate.js, mappings/document.js, mappings/partial/centroid.js, package.json, punctuation.js, schema.js, settings.js, street_suffix.js, test/compile.js, test/document.js, test/partial-centroid.js, test/settings.js
@pelias/owners I'm removing the 'DO NOT MERGE' tag from this repo, it's ready for review and merge now.
The PR ended up becoming quite large, it covers a complete review and re-factoring of our linguistic analysis while also migrating the autocomplete from an FST structure to edgeNgrams+inverted index.
I've also introduced a new type of test suite which can be executed with `npm run integration`, this is a super easy way to test the effects of adding/removing algorithms from the analysis pipeline and it let's you send text string to ES and get back the tokens it produces.
The easiest way to explore the changes is via these tests, there is one for each analyzer:
https://github.com/pelias/schema/tree/ngram/integration
Also included in this PR is
- better support for geohashes …
=> search ngrams

integration/analyzer_peliasPhrase.js, settings.js, test/settings.js
This PR addresses the 'phrase slop' problem as described briefly in https://github.com/pelias/schema/issues/66
The background here is that Pelias uses 2 different linguistic matching techniques when dealing with `names` (there are more for admin areas etc. but that's another story), this only applies to `name` matching (ie. nothing after the first comma)
We have a `prefix ngram` matching analysis which works great for autocomplete but falls short in a couple of areas:
- setting the `min_gram` value to `2` or `3` will discard street numbers grams (eg. `1`, `2b` and/or `11`)
- it is not `phrase aware`, meaning it does not consider the order in which tokens are typed.
- it does not score on `slop`, meaning it does not favour tokens which lie next to each other over those which appear further …
=> phrase slop

integration/analyzer_peliasOneEdgeGram.js, integration/analyzer_peliasTwoEdgeGram.js, settings.js, test/fixtures/expected.json, test/settings.js
increase max ngram size.
tokens such as `grolmanstrasse` and `shuffleboard` were being truncated at 10 chars
=> increase max gram token size

integration/address_matching.js, integration/admin_matching.js, integration/dynamic_templates.js, integration/run.js, mappings/document.js, mappings/partial/foreignkey.json, schema.js, test/compile.js, test/document.js, test/fixtures/expected.json
**[edit]** this PR has been updated in order to support both quattroshapes and WOF *simultaneously* and should now be good-to-release.
this PR changes the terminology used to refer to the 'administrative' hierarchy of geographic regions which parent a document.
prior to this PR these document fields were named:
```
admin0
admin1
admin1_abbr
admin2
local_admin
locality
neighborhood
```
the proposal in this PR is to **add** the following fields:
```
parent.country
parent.country_abbr
parent.country_id
parent.region
parent.region_abbr
parent.region_id
parent.county
parent.county_abbr
parent.county_id
parent.locality
parent.locality_abbr
parent.locality_id
parent.localadmin
parent.localadmin_abbr
parent.localadmin_id
parent.neighbourhood
parent.neighbourhood_abbr
parent.neighbourhood_id
```
I …
=> use WOF placetypes instead of quattroshapes placetypes

integration/address_matching.js, integration/admin_matching.js, integration/dynamic_templates.js, integration/run.js, mappings/document.js, mappings/partial/boundingbox.json, mappings/partial/foreignkey.json, schema.js, test/compile.js, test/document.js, test/fixtures/expected.json
WOF import time was taking 45 minutes, so this PR changes storage of `boundingbox` from `geotype` to unindexed UL/LR string.
Fixes #97
=> Convert boundingbox to string

integration/analyzer_peliasOneEdgeGram.js, integration/analyzer_peliasTwoEdgeGram.js, settings.js, test/fixtures/expected.json, test/settings.js
pretty straight forward, this PR adds the existing `address_suffix_expansion` filter to the `peliasOneEdgeGram` analyzer.
the motivation comes from using the `peliasOneEdgeGram` as our default search analyzer so it's best if it works well when used against and index created using `peliasTwoEdgeGram`
=> add address_suffix_expansion to peliasOneEdgeGram analysis, add tests

schema.js, test/fixtures/expected.json
This will prevent localities and other admin areas from ranking below
counties that have the same name, but lower population.
This hopefully fixes the failing San Francisco acceptance test found in https://github.com/pelias/acceptance-tests/issues/192#issuecomment-199464239
=> Index one-grams for macroregion, macrocounty, localadmin, locality

integration/dynamic_templates.js, mappings/document.js, schema.js, test/compile.js, test/document.js, test/fixtures/expected.json
This is no longer used now that we're 100% on the new schema.
Edit: we should remove the usage of this from wof-admin-lookup and pelias/model first.
Connected to pelias/model#32
Connected to pelias/wof-admin-lookup#38
=> Remove remaining legacy schema

integration/analyzer_peliasIndexOneEdgeGram.js, integration/analyzer_peliasIndexTwoEdgeGram.js, integration/analyzer_peliasPhrase.js, integration/analyzer_peliasQueryFullToken.js, integration/analyzer_peliasQueryPartialToken.js, settings.js, test/fixtures/expected.json, test/settings.js
This PR completely removes the kstem analysis filter, just as an experiment to see what sort of effect it has on search quality.
_Update:_ after running this on dev, I now propose that we actually remove kstem. Full rationale below.
I was a bit amazed when I ran our acceptance tests and found that removing kstem slightly improves the results
I've gone through all the tests to see where the differences are, and here are my conclusions. I'm _really_ looking for people to help by finding other cases that don't work as well on dev right now, as if there are any serious issues, we should hold off on merging this. That said I haven't really found any.
This is the original query that got us looking at kstem. Daly is stemmed to dale which causes dale city to match above daly city
While the full …
=> Remove kstem analysis filter

.travis.yml, integration/analyzer_peliasIndexOneEdgeGram.js, integration/analyzer_peliasQueryFullToken.js, integration/analyzer_peliasQueryPartialToken.js, integration/dynamic_templates.js, integration/validate.js, mappings/document.js, mappings/partial/centroid.js, mappings/partial/literal.json, package.json, schema.js, scripts/info.js, settings.js, test/compile.js, test/document.js, test/fixtures/expected.json, test/partial-centroid.js, test/partial-literal.js, test/settings.js
- add `goldbergianPeliasHousenumber` to ensure that numeric values are treated as whole tokens rather than creating prefixes.
- use single gram analyzers for all fields, no longer using 2 gram analysis
- remove settings deprecated in ES2
- remove `dynamic_templates` so now all `_type` have the same config
=> Elasticsearch2

.gitignore, package.json, scripts/create_index.js, scripts/drop_index.js, scripts/info.js, scripts/output_mapping.js, scripts/reset_type.js, scripts/update_settings.js
Now that the client is [deprecated](https://github.com/pelias-deprecated/esclient) we should stop using it. Fortunately, esclient was mostly a wrapper around the official Elasticsearch client, so this was a straightforward change.
Fixes #144
=> Replace pelias-esclient with official elasticsearch module

scripts/create_index.js, scripts/drop_index.js, scripts/info.js, scripts/output_mapping.js, scripts/reset_type.js, scripts/update_settings.js
One confusing part of `esclient` is that it automatically pulls in `pelias-config`. I know this because I missed the exact same thing when making this change for the API: https://github.com/pelias/api/pull/448
=> Pass config to Elasticsearch

.travis.yml
tests all pass against elasticsearch version `2.3.4`, see [example](https://travis-ci.org/pelias/schema/builds/149168878).
I managed to get it all working without using `sudo` and the builds come in at ~2mins
We should be able to speed up the builds more in the future when the following issues have been addressed:
- https://github.com/travis-ci/apt-source-whitelist/issues/293
- https://github.com/travis-ci/apt-source-whitelist/pull/262
see also: https://github.com/travis-ci/travis-ci/issues/4542
based off: https://gist.github.com/mkorkmaz/254cd7c46a6fbcf79804158b4a6fb013
closes https://github.com/pelias/schema/issues/139
=> run integration tests in travis

README.md, scripts/check_plugins.js, scripts/cli.js, scripts/create_index.js
This PR adds a new script called `./scripts/check_plugins.js` which checks that all mandatory plugins are installed across all nodes in the cluster.
The script is also runs before `./scripts/create_index.js` is run; outputting useful information about how to install any missing plugins:
resolves: https://github.com/pelias/schema/issues/148
=> Plugin script

scripts/output_mapping.js
`process.exit` can truncate long output in certain node versions, see
these tickets:
https://github.com/nodejs/node/issues/3669
https://github.com/nodejs/node/pull/3170
https://github.com/nodejs/node/issues/2972#issuecomment-146078649
fixes #161
=> Rearrange logic in output_mapping

integration/analyzer_peliasAdmin.js, integration/analyzer_peliasIndexOneEdgeGram.js, integration/analyzer_peliasIndexTwoEdgeGram.js, integration/analyzer_peliasPhrase.js, integration/analyzer_peliasQueryFullToken.js, integration/analyzer_peliasQueryPartialToken.js, integration/analyzer_peliasStreet.js, settings.js, test/fixtures/expected.json, test/settings.js
DO NOT MERGE at this time, this PR requires that the `icu plugin` to be installed in elasticsearch in order to work.
Closes https://github.com/pelias/schema/issues/148
More info can be found on the issue above, this PR enables the ICU plugin and uses unicode-aware functions in place of non unicode-aware functions.
In effect this provides support for unicode combining characters and better glyph folding.
=> refactor schema to use icu plugin

package.json
It's required in production but has been living in devDependencies for a
long time since we were installing both.
=> Move elasticsearch to dependencies

integration/analyzer_peliasStreet.js, settings.js, test/fixtures/expected.json
The reason that `186 Tuskegee St SE Atlanta GA` test was failing is because directionals were being contracted with a space appended which is incorrect behavior since postdirectionals are a thing.
=> Remove space appending to directionals

scripts/drop_index.js
Previously, only the first host in `esclient.hosts` was checked for localhost value so if the array contained multiple hosts and the first was not localhost, no warning would be given about dropping a non-localhost index.  For example:
```
{
"env": "development",
"protocol": "http",
"host": "localhost",
"port": 9200
},
{
"env": "production",
"protocol": "http",
"host": "internal-pelias-production-es2-162482742.us-east-1.elb.amazonaws.com",
"port": 9200
}
```
No warning would be given even though it would drop the production index.
=> Add checks for localhost drop

scripts/check_plugins.js
The AWS Elasticsearch service does not expose the list of installed plugins, so our plugin checking code breaks.
Fortunately, for now, it has the plugin we need already installed.
Note that in our testing, Pelias performs significantly worse on the hosted Elasticsearch compared to regular EC2 instances.
See https://github.com/pelias/pelias/issues/402#issuecomment-255854624 for more details
Fixes https://github.com/pelias/schema/issues/213
=> Skip plugin checks on hosted Elasticsearch

scripts/create_index.js
Fixed path to check_plugins.js in create_index.js script to allow run index creation from any working dir only only from schema directory itself.
Fixes https://github.com/pelias/schema/issues/190
=> Fixed path to check_plugins.js in create_index.js

schema.js, test/fixtures/config.json, test/fixtures/expected.json
the schema allows creating new `_types` dynamically using the `_default_` API, we have been using this feature when introducing new layers such as `street`.
there is, however, an advantage to creating the `_type` explicitly. Elasticsearch will error instead of returning 0 results for any `_type` that is requested but is not present in the `_mapping`.
by creating all known layers at schema creating time, we can avoid these sort of errors, this is less relevant for full-planet, all-layer builds and more relevant to smaller builds which only import a subset of layers.
I haven't seen a bug report for it, but I imagine that if someone *only* imported WOF and requested something from a combination of `street` or `region` layers, a 500 level error would be produced rather than simply returning …
=> update schema mappings to include all current layers

.circleci/docker.sh
This will only skip greenkeeper branches, instead of all of them.
Connects https://github.com/pelias/dockerfiles/issues/21
=> Fix CircleCI code to skip builds on greenkeeper branches

mappings/document.js, settings.js, test/document.js, test/fixtures/expected.json, test/settings.js
To resolve https://github.com/pelias/pelias/issues/618 more details found in comments to that issue
=> Adding address unit attribute to schema

package.json, settings.js
[pelias-mergeable](https://github.com/pelias/mergeable/) is to be deprecated, so replace usage with the functionality provided by `lodash`.
Given we only require a small subset of lodash, add dependency for `lodash.merge` to avoid pulling in an unnecessarily large dependency.
See further the objective in: https://github.com/pelias/mergeable/issues/5
=> Replace pelias-mergeable with lodash.merge

settings.js, synonyms/custom_admin.txt, synonyms/custom_name.txt, synonyms/custom_street.txt, synonyms/parser.js, test/fixtures/expected.json, test/run.js, test/settings.js, test/synonyms/parser.js
note: this PR was branched off https://github.com/pelias/schema/pull/272, please merge that PR first.
diff between this branch and the parent: https://github.com/pelias/schema/compare/synonyms...custom_synonyms
This PR follows on from the synonyms refactoring in https://github.com/pelias/schema/pull/272 by adding user-modifiable synonyms files in-place, ready to be used:
```bash
$ ls -1 synonyms/custom_*
synonyms/custom_admin.txt
synonyms/custom_name.txt
synonyms/custom_street.txt
```
For now, these files are empty, we will be accepting community PRs to improve the synonyms that end up in these files.
The idea with the naming is that the 'custom_name.txt' file applies to the 'name' field in the mapping, same for 'street' and 'admin'.
=> Custom synonyms

settings.js
Hi there,
thanks for adding extremely useful thing such a separate files for elasticsearch synonyms.
I've noticed that currently it could be problematic to work with this module if run scripts from outside of module folder. This PR adds simply __dirname to path to this folder and in the end it will be absolute path which looks much more safety.
=> fix(settings.js): fix relative path to folder with synonyms

mappings/document.js, test/document.js, test/fixtures/expected.json
We added continents to pelias/model in https://github.com/pelias/model/pull/48, so our importers now ask Elasticsearch to create records with fields for continents.
At the moment, looking at https://github.com/pelias/pelias/issues/473 and associated issues, it doesn't appear we ever add any data to the continent fields. Whether or not we want to do that is worth discussing.
However, without adding continents to the Elasticsearch mapping, Elasticsearch will add all of these continent fields as string mappings:
```
julian@manhattan ~/repos/pelias/schema $ curl -s localhost:9200/pelias | jq . | grep continent -C 3
"store": true,
"analyzer": "keyword"
},
"continent": {
"type": "string"
},
"continent_id": {
"type": "string"
},
```
This isn't ideal, even if no continents are ever added to the …
=> Add continent and empire to parent field mappings

package.json
I'm not sure why these were not running, considering we had all the support to set up Elasticsearch turned on. I couldn't even find a time in the file history where they _were_enabled.
=> Re-enable Integration tests on TravisCI

bin/integration, bin/test, package.json
The way we were running our unit tests does not catch fatal errors in the unit test run, even though they return non-zero status codes.
By using a dedicated script to run the tests, with the `pipefail` option, we can catch them.
Connects https://github.com/pelias/pelias/issues/744
=> feat(test): Use test running binary to catch errors

README.md
update docs to use official Pelias docker image which also includes the ICU plugin
=> feat(docs): use Pelias maintained docker image for testing

mappings/partial/centroid.js, test/fixtures/expected.json, test/partial-centroid.js
remove geo_point properties deprecated in 2.3 or 2.4
- https://www.elastic.co/guide/en/elasticsearch/reference/2.4/geo-point.html#geo-point-params
- https://www.elastic.co/guide/en/elasticsearch/reference/2.4/release-notes-2.4.0.html
=> remove geo_point properties deprecated in 2.3 or 2.4

mappings/document.js, test/compile.js, test/document.js, test/fixtures/expected.json
Fieldata is only used for aggregations, sorting (by the string value of a field), and scripts. Pelias does not use any of those.
Currently, a full planet Pelias build has about 40GB of fielddata loaded into memory, but it's never used. So this is a significant savings potential.
We'll want to test this on larger builds to get a sense of the memory savings and any other possible side effects.
Fixes https://github.com/pelias/schema/issues/100
=> Disable fielddata for name.* and phrase.* fields

.circleci/config.yml, .travis.yml, package.json
Several changes regarding CI and Node.js versions:
- CI Docker script now requires bash
- Support for Node.js 6 has been dropped (https://github.com/pelias/pelias/issues/752)
- Semantic-release was running (doing nothing but taking up build time) on all pull requests for no reason
- Releases are now run directly off the master branch (https://github.com/pelias/pelias/issues/749)
=> CI and Node.js Update

mappings/partial/admin.json, mappings/partial/boundingbox.json, mappings/partial/literal.json, mappings/partial/postalcode.json, test/fixtures/expected.json, test/partial-admin.js, test/partial-literal.js
Background
==========
I always thought that it was important to use the `store` parameter to specify whether a field should be stored, in addition to indexing, and the default was to not store a field for later retrieval.
It turns out this isn't true, and that all fields are [copied to the _source](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/mapping-store.html) field by default.
Setting `"store": "yes"` is only needed if, in addition to getting a field back as part of the `_source` (which contains _every_ field in the document), we wanted to be able to return a single field. Pelias
doesn't currently do this, we always ask Elasticsearch for the entire `_source` field.
In addition, Elasticsearch has a [source filtering](https://www.elastic.co/guide/en/elasticsearch/reference/ …
=> feat(mapping): Remove `store` mapping parameter

mappings/document.js, mappings/partial/literal.json, mappings/partial/literal_with_doc_values.json, test/document.js, test/fixtures/expected.json, test/partial-literal.js
As long suspected in #99, turns out there _are_ differences between setting `"index": "not_analyzed"` for a field, and merely setting the analyzer to `keyword`.
They are detailed in the Elasticsearch 2.4 [String datatype](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/string.html#string-params) documentation, although it's a little bit confusing.
In Elasticsearch 5+, there are _two_ different types of string datatypes:
- [`text`](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/text.html)
- [`keyword`](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/keyword.html)
These documentation pages make the difference much more clear. In short, in Elasticsearch 2.4, setting `"index": "not_analyzed"` gives the following changes, all of which we'd like for these …
=> feat(mapping): use "index": "not_analyzed" for literal fields

integration/admin_matching.js, mappings/document.js, test/document.js, test/fixtures/expected.json
We stopped using the `alpha3` field over [two years ago](https://github.com/pelias/query/pull/6), but it was still lingering in our schema including some tests.
This was discovered while updating and testing https://github.com/pelias/schema/pull/282.
=> feat(mapping): Remove unused `alpha3` field

integration/admin_matching.js, mappings/document.js, test/document.js, test/fixtures/expected.json
Strict [dynamic mapping](https://www.elastic.co/guide/en/elasticsearch/guide/current/dynamic-mapping.html) tells Elasticsearch to throw an exception whenever an attempt to index a field not specified in the type mapping is made.
By setting dynamic mapping to true, we missed issues such as [continents being added to the model, but not schema](https://github.com/pelias/schema/pull/281). Using strict mapping should help us catch issues like this in the future.
=> Use strict mapping

mappings/document.js, test/document.js, test/fixtures/expected.json
These were missed and never fixed because until recently, we did not use a strict schema mapping (see https://github.com/pelias/schema/pull/282).
_sidenote_: all these very similar mapping fields is getting very tiresome. Maybe we look into some dynamic_templates.
=> fix(parent): Add ocean and marinearea to parent fields

.travis.yml, README.md, bin/create_index, bin/integration, package.json, scripts/create_index.js
This provides a decent solution to the issues of compatibility with Node.js 8.14+/10.14+ and Elasticsearch 5.
It includes updates to code and documentation requiring Node.js 8.15 or 10.15, which includes a `--max-http-header-size` parameter. By creating a `create_index` wrapper script that always passes a safe value for that parameter, we can ensure that the high number of Elasticsearch 5 deprecation warning headers don't cause issue with the header size limits introduced in Node.js.
The `create_index.js` script itself now also checks for reasonable values of that parameter, and will warn if the value is non-existent (suggesting an old version of Node.js is in use) or set to the default value (in which case the issue will occur if Elasticsearch 5 is in use).
Once we drop support for …
=> Use header size parameter

integration/dynamic_templates.js, mappings/document.js, test/document.js, test/fixtures/expected.json
This PR addresses the issue mentioned in https://github.com/pelias/pelias/issues/747, also known as 'custom data'.
This change would allow the operators of a Pelias instance to store arbitrary data alongside any document.
The intention here is that the field `addendum` is of type `map[string]string`, with each entry being namespaced in order to avoid property collision.
It's intended that the value of the field is encoded as a string (although the codec nor the data type are actually enforced here).
paired with:
- https://github.com/pelias/model/pull/112
- https://github.com/pelias/api/pull/1255
resolves https://github.com/pelias/pelias/issues/747
=> allow arbitrary data to be stored alongside the rest of the document

scripts/check_plugins.js
The name of the Elasticsearch plugin management binary changed from `plugin` with ES2 and older, to `elasticsearch-plugin` in ES5 and newer.
This PR allows detecting the proper plugin name so that any instructions printed for users to follow are as accurate as possible. It's designed so that the ES2 specific code can be easily removed as we drop support for ES2.
Connects https://github.com/pelias/pelias/issues/461
=> Use correct plugin binary for Elasticsearch version

mappings/partial/admin.json, mappings/partial/postalcode.json, package.json, test/compile.js, test/document.js, test/fixtures/expected.json
This PR is a replacement for https://github.com/pelias/schema/pull/345 which uses the [multi-fields](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/multi-fields.html) feature of elasticsearch in order to achieve the same thing but using less HDD space.
See linked PR for original issue notes and comments.
Closes https://github.com/pelias/schema/pull/345
=> Compute an ngram field for all admin data

integration/analyzer_peliasPhrase.js, integration/analyzer_peliasStreet.js, synonyms/street_suffix.txt, test/fixtures/expected.json, test/settings.js
A user reported that `Aufderhöher Str` is not synonymous with `Aufderhöher Straße` and `Aufderhöher Strasse`.
This PR adds street suffix synonyms for common Germanic street names.
It doesn't handle contracted and expanded version of compound words as per `Aufderhöherstr.` or `Aufderhöherstraße`.
=> update Germanic street suffix synonyms

integration/analyzer_peliasPhrase.js, integration/analyzer_peliasStreet.js, synonyms/street_suffix.txt, test/fixtures/expected.json
We had a synonym for Avenue->Ave, but not Av, which is another common abbreviation.
Connects https://github.com/pelias/schema/issues/335
=> feat(synonyms): Add Avenue->Av synonym

synonyms/street_suffix.txt, test/fixtures/expected.json
We already had the `tr` abbreviation for Trail, but not `trl`, which is also common.
Connects https://github.com/pelias/pelias/issues/456
=> feat(synonyms):Add Trl/Trail

integration/analyzer_peliasIndexOneEdgeGram.js, integration/analyzer_peliasPhrase.js, integration/analyzer_peliasQueryFullToken.js, integration/analyzer_peliasQueryPartialToken.js, settings.js, test/fixtures/expected.json, test/settings.js
I discovered a bug today which can cause `match_phrase` queries to fail in certain situations.
I was investigating the query `SE 23rd Ave & SE Madison St` and discovered that the `unique` token filter was stripping the first `SE` token, and since the second `SE` token position was too far away according to the `slop` value, it failed to match the input `23rd Ave & SE Madison St`.
A simplified example is something like this (with token positions shown):
```
input: 'A AB'
['0:A', '0:AB'] // before
['0:A', '1:A', '1:AB'] // after
```
The first 'A' ngram would be removed and also the other token positions would be incorrect as a result!
I'm not sure about the full extent of how many queries this affects but I suspect it causes jitter issues.
Only `phrase` type queries are affected and it's …
=> unique token filter bugfix

integration/analyzer_peliasIndexOneEdgeGram.js, integration/analyzer_peliasPhrase.js, integration/analyzer_peliasQueryFullToken.js, integration/analyzer_peliasQueryPartialToken.js, synonyms/ampersand.txt, test/fixtures/expected.json, test/settings.js
~~Branched from https://github.com/pelias/schema/pull/367, need to merge that PR first.~~
This PR improves how we support the ampersand symbol:
- Allow prefix ngrams to be produced, so that an input of `an` in autocomplete will match `&`
- Add support for German language
I did some investigation and it turns out that the ampersand symbol isn't as common internationally as I suspected.
For now, we support English and German but open to supporting more languages where required.
Resolves https://github.com/pelias/schema/issues/366
This is also the last 'old style' synonyms file which uses '=>' rather than ',' for substitutions 🎉
=> Improved ampersand support

integration/analyzer_peliasQuery.js, integration/run.js, settings.js, test/fixtures/expected.json, test/settings.js
We have two 'query-time' analyzers right now:
- peliasQueryPartialToken
- peliasQueryFullToken
The difference between these analyzers is due to how the synonyms substitutions are handled.
Some time ago we made a change to how synonyms are applied in schema, so instead of 'expanding' or 'contracting' like we used to do, we now allow pure synonym substitution where either/or version of the token will match.
So this means that query-time synonym generation is no longer required as all versions are available in the index.
I started doing the work to remove the synonyms filter and realised quickly that `peliasQueryPartialToken` and `peliasQueryFullToken` would now do exactly the same thing, albeit under a different name.
I would like to remove both of those analyzers as they are just confusing …
=> Simplify query-time analysis

bin/integration, integration/dynamic_templates.js, mappings/document.js, mappings/partial/admin.json, mappings/partial/keyword.json, mappings/partial/keyword_with_doc_values.json, mappings/partial/literal.json, mappings/partial/literal_with_doc_values.json, mappings/partial/postalcode.json, scripts/create_index.js, test/compile.js, test/document.js, test/fixtures/expected.json, test/partial-admin.js, test/partial-keyword.js, test/run.js
This change makes our Elasticsearch schema compatible with Elasticsearch 5 and 6. It shouldn't have any effect on performance or operation, but it will completely drop compatibility for Elasticsearch 2.
The primary change is that Elasticsearch 5 introduces two types of text fields: `text` and `keyword`, whereas Elasticsearch 2 only had 1: `string`.
Roughly, a `text` field is for true full text search and a `keyword` field is for simple values that are primarily used for filtering or aggregation (for example, our `source` and `layer` fields). The `string` datatype previously filled both of those roles depending on how it was configured.
Fortunately, we had already roughly created a concept similar to the `keyword` datatype in our schema, but called it `literal`. This has been renamed to …
=> Update schema for Elasticsearch 5 and 6 

synonyms/street_suffix.txt, test/fixtures/expected.json
:wave: I did some awesome work for the Pelias project and would love for everyone to have a look at it and provide feedback.
---
I came across an example yesterday "39 Bellavista tce, Paddington, Queensland 4064, Australia"
It seems only "terrace" and "terr" are currently synonyms so tce doesn't match and causes a bad geocode.
https://pelias.github.io/compare/#/v1/search%3Ftext=39%20Bellavista%20tce,%20Paddington,%20Queensland%204064,%20Australia
Checking my database of 5 million real world (mostly Australian) addresses I have:
- 47133 ending with "terrace"
- 6333 ending with "tce"
- 6 ending with "terr"
---
Added tce as a synonym of terrace.
=> Add "tce" as a synonym of terrace

integration/analyzer_peliasAdmin.js, integration/analyzer_peliasIndexOneEdgeGram.js, integration/analyzer_peliasPhrase.js, integration/analyzer_peliasQueryFullToken.js, integration/analyzer_peliasQueryPartialToken.js, integration/analyzer_peliasStreet.js, integration/run.js, package.json, settings.js, test/document.js
okay, so there are a bunch of changes in here but it should be a no-op refactor ;)
this PR enforces strict checking of token positions for the `integration` test suite.
the motivation for this is:
- the order in which tokens are generated by elasticsearch changed in elasticsearch@6 making all the tests break
- not specifying token positions in the test meant they were not checked, meaning nasty bugs could slip through unnoticed.
you can provide the 'expected' tokens in two forms:
```
// no explicit token positions
[ 'A', 'ABC' ]
or...
// with explicit token positions
[ '0:A', '1:ABC' ]
```
prior to this PR if you used the 'no explicit token positions' form then we simply checked that all the tokens were present and there were no extra ones being generated.
what it's doing now is assigning …
=> enforce strict checking of token positions

settings.js, test/fixtures/expected.json, test/settings.js
fix mandatory token filter test and refactor schema to enforce original intent.
there is an acceptance test which was supposed to ensure that *every* analyzer contains all of the mandatory token filters such as `lowercase` `unique` etc.
looking at this code today it was all messed up and not testing what it should have been, as a result, some of the analyzers were missing some of these very basic but very essential components (although I doubt the effect was noticeable).
In the process of fixing the test I've also refactored the token filters in order to achieve the original intent of the test.
=> fix mandatory token filter test

integration/analyzer_peliasIndexOneEdgeGram.js, settings.js, test/fixtures/expected.json, test/settings.js
This removes the complex filtering logic known as the "complicated housenumber filter", or sometimes even the "goldbergian housenumber filter", originally described in https://github.com/pelias/schema/pull/133 and merged as part of our ES2 upgrade (https://github.com/pelias/schema/pull/138).
The housenumber filter was made quite a long time ago, with the intention of removing partial numeric tokens.
It's a lot of code, rather hard to understand, and may actually cause more problems than it solves.
Since this code was written, we've improved autocomplete considerably, and having some tokens missing could be resulting in autocomplete not doing its job as well as it could.
In particular, fully numeric postal codes cannot be found with autocomplete until the postal code is entered completely …
=> Remove complicated housenumber filter

integration/multi_token_synonyms.js, integration/run.js, settings.js, test/fixtures/expected.json, test/settings.js
add [flatten_graph](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-flatten-graph-tokenfilter.html) token filter to ensure multi-word tokens dont produce errors during indexing.
this PR resolves https://github.com/pelias/schema/issues/381 and closes https://github.com/pelias/schema/pull/388 as an alternative.
this method was alluded to in the [elastic blogpost](https://www.elastic.co/blog/multitoken-synonyms-and-graph-queries-in-elasticsearch):
> If for some reason you really need exactly the same behavior as the old SynonymFilter then you should create a SynonymGraphFilter followed by a FlattenGraphFilter, but just remember that FlattenGraphFilter necessarily throws something (the full graph structure) away!
.. although that references a `synonym_graph` filter …
=>  add flatten_graph filter to allow multi-word tokens on ES6

.travis.yml, scripts/elastic_wait.sh, scripts/setup_ci.sh
This PR modernizes our Travis-CI config.
I had numerous problems testing Elasticsearch6 & 7 using the existing config, I've managed to backport that code to target `master`
Highlights:
- switch to `bionic` from `trusty`
- test multiple supported versions of ES (current & future)
- test multiple JVM versions (current & future long-term releases)
Probably doesn't look like many changes but took 4 hours to get this working and numerous Travis builds ☹️
=> fix(CI): update Travis-CI

scripts/elastic_wait.sh, scripts/setup_ci.sh
I think my previous PR was using `elastic_wait` incorrectly.
The script exits 0 or 1, which was preventing the rest of the `setup_ci` script from running after the `elastic_wait` command ended
=> update elastic_wait command usage

README.md
There were previously strict Node.js version compatibility issues with the schema.
However, once we dropped support for Elasticsearch 2 in https://github.com/pelias/schema/pull/372, this was no longer required.
=> feat(docs): Remove obsolete compatibility note

.travis.yml, integration/address_matching.js, integration/admin_matching.js, integration/analyzer_peliasPhrase.js, integration/analyzer_peliasQueryFullToken.js, integration/autocomplete_abbreviated_street_names.js, integration/autocomplete_directional_synonym_expansion.js, integration/autocomplete_street_synonym_expansion.js, integration/bounding_box.js, integration/dynamic_templates.js, integration/multi_token_synonyms.js, integration/source_layer_sourceid_filtering.js, integration/validate.js, scripts/setup_ci.sh, test/compile.js
this PR updates our CI config to test multiple `schema.typeName` values so that we will know when a PR which breaks backwards compatibility with ES5 is opened.
I ended up modernizing a bunch of this code and also dropping node8 from the build matrix since it got very large!
=> test multiple type names

mappings/partial/shape.json, scripts/setup_ci.sh, settings.js, test/fixtures/expected.json
backport some features from the ES7 branch which may be ok to use now
note: this includes the code which moves `word_delimiter` down one place, I'm not against removing that line as suggested in the draft PR https://github.com/pelias/schema/pull/392, I just wanted to keep this as close to a no-op as possible for now.
merging this will ensure that indices built on ES6 are more compatible with future versions, hopefully avoiding breaking changes down the line.
our new epic build matrix will catch any bugs ;)
=> backport some features from the ES7 branch which may be ok to use now

.travis.yml, README.md, scripts/setup_ci.sh
minor README edit to update the preferred ES version for testing
[edit] I got the version wrong, the most up-to-date version is `6.8.5` so I've also updated Travis to reflect that.
[edit] includes fix for ES bug in `6.8.5` release.
=> update preferred ES version

mappings/document.js, mappings/partial/admin.json, mappings/partial/postalcode.json, test/compile.js, test/document.js, test/fixtures/expected.json
cherry-picked from https://github.com/pelias/schema/pull/412 and based on https://github.com/pelias/schema/pull/413. [view diff](https://github.com/pelias/schema/compare/list_analyzers...explicitly_set_analyzers)
This is something I've been wanting to do for a while, it explicitly sets the `analyzer` and `search_analyzer` property for all `text` fields.
The default behaviour of elasticsearch is to default all analyzers to `standard` when not otherwise defined..
... and to default the `search_analyzer` property to equal `analyzer`.
So while it's not totally necessary to define an explicit `search_analyzer` when it's equal to the `analyzer` I have made this mandatory and covered it with tests, this ensures that it is considered when adding new fields or adapting existing ones.
This is …
=> Explicitly set analyzers

integration/_hits_total_helper.js, integration/address_matching.js, integration/admin_matching.js, integration/analyzer_peliasPhrase.js, integration/autocomplete_abbreviated_street_names.js, integration/autocomplete_directional_synonym_expansion.js, integration/autocomplete_street_synonym_expansion.js, integration/source_layer_sourceid_filtering.js
In Elasticsearch 7+, the [hits count is now an object](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#hits-total-now-object-search-response).
This was needed because Elasticsearch now includes a performance improvement that allows non-exact hit counts to be used when the exact count isn't needed.
This PR adds a helper to wrap around the breaking change and support either the old or new format.
Extracted from https://github.com/pelias/schema/pull/394
=> feat(integration): Add total hits helper

.travis.yml
BREAKING CHANGE: This drops Elasticsearch 5 from the test matrix for this repo. While it makes no other changes, it's a breaking change as it marks the point where we stop supporting ES5.
This allows us to make changes that support only ES6/7 as we add support for Elasticsearch 7.
=> feat(ES5): Drop support for Elasticsearch 5

package.json
Node.js 8 is no longer supported as it will reach [end of life](https://github.com/nodejs/Release#release-schedule) at the end of 2019.
Unlike the other PRs to drop Node.js 8 support, this one was not made a breaking change since we just dropped ES5 support, also as a breaking change.
Connects https://github.com/pelias/pelias/issues/837
=> feat(Node.js): Drop support for Node.js 8

integration/address_matching.js, integration/admin_matching.js, integration/analyzer_peliasAdmin.js, integration/analyzer_peliasHousenumber.js, integration/analyzer_peliasIndexOneEdgeGram.js, integration/analyzer_peliasPhrase.js, integration/analyzer_peliasQuery.js, integration/analyzer_peliasStreet.js, integration/analyzer_peliasZip.js, integration/autocomplete_abbreviated_street_names.js, integration/autocomplete_directional_synonym_expansion.js, integration/autocomplete_street_synonym_expansion.js, integration/bounding_box.js, integration/dynamic_templates.js, integration/multi_token_synonyms.js, integration/run.js, integration/source_layer_sourceid_filtering.js, integration/validate.js
After looking at the changes in https://github.com/pelias/schema/pull/394, I noticed that all the parameters used to create test indices during the integration tests were identical.
Because we will want to make changes to those options as part of our move to support Elasticsearch 7, this PR is a pure refactoring that moves those options to the `common` object passed to each integration test.
This should allow us to make any future changes to index creation options in a single place.
=> chore(integration): Move schema creation options to common config

.travis.yml
This drops support for testing the schema with the Elasticsearch type name set to `doc`. This was only needed to support Elasticsearch 5. In order to support Elasticsearch 7, we'll no longer be supporting ES5.
=> chore(CI): Remove old Elasticsearch type support (`doc`) from CI

.travis.yml
This adds Elasticsearch 7.5.1 to the CI test matrix. Until we merge complete support for ES7, this CI run is allowed to fail without failing the entire build.
=> chore(CI): Add Elasticsearch 7 to CI

integration/dynamic_templates.js, integration/run.js, schema.js, scripts/create_index.js, test/compile.js, test/fixtures/expected.json
In ES7, specifying a mapping type name when defining index will no longer be allowed by default. ES6 can emulate this behavior by setting the `include_type_name` parameter to `false` when creating and fetching mappings.
This PR sets that parameter so that our mapping format uses the ES7 preferred format, while still maintaining compatibility with ES6.
In the future, when we wish to drop support for ES6, we'll only have to stop using the `include_type_name` configuration option.
=> feat(ES7): Remove type name from mapping configuration

mappings/document.js, test/document.js, test/fixtures/expected.json
The `_all` field was deprecated in Elasticsearch 6 and completely removed in [Elasticsearch 7](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#all-meta-field-removed).
Pelias has disabled this field for quite some time, however now that we have dropped support for ES5, we can remove this configuration option.
This happens to be the final change required to add support for ES7! :tada: 
=> feat(es7): remove _all mapping

.travis.yml
Quickly following up from https://github.com/pelias/schema/pull/422, this requires the Elasticsearch 7 tests to pass, now that we have merged all changes required to add Elasticsearch 7 support.
=> chore(tests): Require ES7 tests to pass

package.json, scripts/check_plugins.js, scripts/check_version.js, scripts/cli.js, scripts/create_index.js
this PR adds a new script which checks the ES version of the server before attempting to create the schema.
it provides a more user-friendly error when encountering an unsupported version:
inspired by https://github.com/pelias/schema/issues/428
=> add check_version.js script

.travis.yml, scripts/setup_ci.sh
Now that we have dropped support for Elasticsearch 5 and the `doc` type, we can remove this CI configuration variable as well.
=> chore(CI): Remove ES_TYPE var

scripts/setup_ci.sh
We definitely do not support such an old version any more, so this download code can go away.
=> chore(CI): Remove logic to handle Elasticsearch 2.4 downloads

.travis.yml, scripts/setup_ci.sh
Elasticsearch 6.8.6 has been released, so we can upgrade our CI to test against that version and remove some extremely frustrating code to work around a [release glitch in ES 6.8.5](https://github.com/elastic/elasticsearch/issues/49599).
=> Upgrade CI to elasticsearch 6.8.6

.travis.yml
_Extracted from https://github.com/pelias/schema/pull/394_
As Elasticsearch 7 will come with JDK 11 out of the box, we will eventually not care about JDK 8 support.
Once we are ready to drop that support, we can merge this PR.
=> chore(CI): remove oraclejdk8 from test matrix

synonyms/linter.js
Just some quick improvements to add a bit more detail to the synonyms linter output. I think this should make it more clear where and how people can fix these warnings if they arise.
Some example output now:
This is a PR into #447
=> Add more information to synonyms linter output

settings.js, test/fixtures/expected.json
this is a purely cosmetic refactor that simplifies the schema a little.
at some point our two tokenizers `peliasNameTokenizer` and `peliasStreetTokenizer` became the same in all but name.
this PR merges them together into a single tokenizer named `peliasTokenizer`.
=> merge duplicate tokenizers

mappings/document.js, test/document.js, test/fixtures/expected.json
change query-time analyzer for street fields to peliasQuery
as discussed in https://github.com/pelias/api/pull/1444
closes https://github.com/pelias/schema/issues/454
=> change query-time analyzer for street fields to peliasQuery

.travis.yml, scripts/create_index.js
BREAKING CHANGE: creating *new* Pelias indices using elasticsearch 6 is no longer supported
see https://github.com/pelias/pelias/issues/881
Attempting to run `create_index.js` against a `pelias/elasticsearch:6.8.5` server results in the following error:
```bash
node scripts/create_index.js
--------------
create index
--------------
unsupported elasticsearch version. try: >=7.4.2
```
=> remove support for creating indices using Elasticsearch 6.x

integration/analyzer_peliasPhrase.js, settings.js, test/fixtures/expected.json, test/settings.js
This change adds the `removeAllZeroNumericPrefix` filter to the `peliasPhrase` analyzer. The idea is to help ensure postalcodes with a leading zero can show up in autocomplete queries, as reported in https://github.com/pelias/pelias/issues/898.
The change is based on two assumptions:
- We want the `peliasPhrase`, `peliasQuery`, and `peliasIndexOneEdgeGram` analyzers to all handle leading zeros similarly
- We _do_ want to remove leading zeros in our analyzers
I recall the original motivation for removing leading zeros is that we sometimes see street names like `05th avenue` in various data sources (or possibly queries), and we want to allow that to match on `5th avenue`.
The original code to do this seems to have been written pretty long ago so it's hard to say for sure.
Anyway, assuming …
=> Add filter to remove leading zeros to `peliasPhrase` analyzer

.github/workflows/push.yml
We normally try to keep all our CI configurations identical, but the schema repository is a bit of a special case since it has to do so many extra things around Elasticsearch.
Apparently, one of those extra things, `npm install -g npm`, now installs a new enough version of NPM that it doesn't work on Node.js 12.
We are removing Node.js 12 support globally soon anyway in https://github.com/pelias/pelias/issues/950,
so we might as well remove it here to make all the tests pass again.
=> CI: Remove Node.js 12 from build matrix

.github/workflows/_integration_tests.yml, .github/workflows/_unit_tests.yml, .github/workflows/pull_request.yml, .github/workflows/push.yml
This updates CI configuration for this repo with the following changes:
- the core configuration for running unit tests and integration tests are moved to separate files for reuse
- a new pull request workflow is added that only runs on external forks, and runs unit/integration tests
- Ubuntu versions are now pulled from a GitHub Actions variable (see https://github.com/pelias/pelias/issues/951)
=> CI: Update GitHub Actions config for uniformity

.github/workflows/_integration_tests.yml, .github/workflows/_unit_tests.yml, .github/workflows/push.yml
I originally intended to trigger a multiarch build with an empty commit, however it was necessary to remove the `npm install -g npm` line due to `nodejs 16` only supporting `npm 9`.
I've also taken the opportunity to update some of the versions used for testing.
=> trigger docker multiarch build

integration/address_matching.js, integration/admin_abbreviations.js, integration/admin_matching.js, integration/analyzer_peliasAdmin.js, integration/analyzer_peliasHousenumber.js, integration/analyzer_peliasIndexOneEdgeGram.js, integration/analyzer_peliasPhrase.js, integration/analyzer_peliasQuery.js, integration/analyzer_peliasStreet.js, integration/analyzer_peliasZip.js, integration/autocomplete_abbreviated_street_names.js, integration/autocomplete_directional_synonym_expansion.js, integration/autocomplete_street_synonym_expansion.js, integration/bounding_box.js, integration/dynamic_templates.js, integration/multi_token_synonyms.js, integration/source_layer_sourceid_filtering.js, integration/validate.js, package.json, test/elastictest/Suite.js
I've archived https://github.com/missinglink/elastictest and pulled the `Suite.js` file into this repo.
It turned out no other repos used that npm module so including the src in this module directly makes maintenance and updates of that code easier since it's in the same place as the implementation.
cc/ @michaelkirk, I will pull your PR commits over here too.
=> integration: merge elastictest into this module

.github/workflows/_integration_tests.yml, .github/workflows/_unit_tests.yml, .github/workflows/push.yml, scripts/create_index.js
:wave:
I was working on something and realised that `create_index.js` doesn't work on modern Node versions... Also decided to update CI to run on Node 18/20/22 and removed Node 16 (let me know if you think it is still needed, but IMO it is too outdated )
=> Bump NodeJs version on CI, fix compatibility with Node >20 in tests

.github/workflows/_integration_tests.yml, .github/workflows/_unit_tests.yml, .github/workflows/push.yml
This PR includes a bunch of commits made by a script that standardizes as much as possible our CI config across all repositories.
Along the way it also ensures we test all Node.js versions that are an LTS release, not EOL, and currently work with this repository. Any Github Actions that were out of date or used old Node.js versions (checkout and setup-node @v2) are also updated.
For the schema repository,  20 and 22 support was added in #497, so fortunately we were already totally up to date with Node.js versions, so nothing had to be done.
Also, the CI OS version is now hardcoded to `ubuntu-22.04`. We fooled around with an organization wide CI variable to configure that, but it broke CI in forks and doesn't really help us much, so it's now undone.
The schema repository is a bit of a …
=> Update Ubuntu and other Github Action versions in CI

integration/analyzer_peliasQuery.js
:wave: I did some awesome work for the Pelias project and would love for everyone to have a look at it and provide feedback.
---
There are some questions in discussion of this PR https://github.com/pelias/schema/pull/498, so I'd like to propose to extend a bit existing test harness to kind of document current state of the things. So current schema:
- tokenizes by whitespace, hyphen, slashes (but doesn't by "dash" character for example - I'd expect ICU tokenizer to work differently here btw 🤔 )
- normalizes thai digits to Arabic ones (I think we can extrapolate it to any other digits writing system)
- removes tonal marks in Thai script
- we never make digits "glued" to the end of word a separate token
- we don't tokenize Asian languages which don't use whitespaces properly
---
- Added …
=> Add some more test cases for tokenization and ascii folding

.github/workflows/_integration_tests.yml, scripts/setup_ci.sh
For quite some time we have configured a specific version of the JDK in our CI.
As far as I understand it, modern versions of Elasticsearch use a bundled version of the JDK so this configuration may no longer be relevant.
On a practical/security note: it also looks like [the scripts](https://github.com/michaelklishin/jdk_switcher) used to switch JDK versions are over 4 years old, and just calling a bash script from a 3rd party repository is a bit scary.
I don't see any changes due to the removal of this option, is it possible we don't need it anymore? @missinglink what do you think?
=> Remove JDK configuration from CI
